# Generated by Django 4.1.7 on 2023-04-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotofrafia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotofrafia',
            new_name='data_fotografia',
        ),
    ]
